ROLE_SUPER_ADMIN = "Super Administrador"
ROLE_ADMIN = "Administrador"
ROLE_VENDEDOR = "Vendedor"

ALL_ROLES = [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_VENDEDOR]

MOVIMIENTO_INGRESO = "INGRESO"
MOVIMIENTO_SALIDA = "SALIDA"

DIAS_ALERTA_VENCIMIENTO = 30
